openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
  description: ユーザー管理機能のAPI定義
paths:
  /api/users:
    $ref: './paths/api_users.yaml'
  /api/users/{id}:
    $ref: './paths/api_users_id.yaml'

components:
  schemas:
    User:
      $ref: './schemas/user.yaml'
    CreateUserRequest:
      $ref: './request/create_user.yaml'
    UpdateUserRequest:
      $ref: './request/update_user.yaml'
    ListUsersResponse:
      $ref: './response/list_users.yaml'